modLoader = "kotlinforforge"
loaderVersion = "[3,)"
issueTrackerURL = "${mod_issue_tracker}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
description = '''${mod_description}'''
authors = "${mod_author}"
logoFile = "drop_confirm.png"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true

[[dependencies.${mod_id}]]
modId = "unilib"
versionRange = "[1.1.0,)"
mandatory = true
side = "CLIENT"
