modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/pupbrained/drop-confirm/issues"
license = "Unlicense"

[[mods]]
modId = "drop_confirm"
version = "4.1.0"
displayName = "DropConfirm"
description = '''Think before you drop.'''
authors = "pupbrained"
logoFile = "drop_confirm.png"

[[dependencies.${ mod_id }]]
modId = "neoforge"
type = "required"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "minecraft"
type = "required"