modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "${license}"

[[mods]]
modId = "drop_confirm"
version = "${version}"
displayName = "${mod_name}"
logoFile = "assets/drop_confirm/drop_confirm.png"
authors = "${mod_author}"
description = '''${description}'''

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies.drop_confirm]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.drop_confirm]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
